[project]
authors = ["Marc Schneider marc@shnei.de"]
description = "PatentPolish"
name = "patentpolish"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64"]

[tasks]
main = "python -m patentpolish"
frontend = "streamlit run src/patentpolish/frontend.py"

[pypi-dependencies]
pymupdf = ">=1.24.10,<2"
patentpolish = { path = ".", editable = true }
opencv-python = ">=4.10.0, <5"
selenium-wire = ">=5.0.0,<6"
openai = ">=1.40.0,<2"

[dependencies]
python = ">=3.11,<4"
pyyaml = ">=6.0.2,<7"
python-dotenv = "*"
loguru = "*"
streamlit = ">=1.38.0,<2"
pypdf = ">=5.0.0,<6"
pydantic = ">=2.9.2,<3"
requests-oauthlib = ">=2.0.0,<3"
requests = ">=2.32.3,<3"
tesseract = ">=5.4.1,<6"
pytesseract = ">=0.3.13,<0.4"
einops = ">=0.8.0,<0.9"
torchvision = ">=0.19.1,<0.20"
transformers = ">=4.45.1,<5"
accelerate = ">=0.34.2,<0.35"
selenium = ">=4.11.2,<5"
python-chromedriver-binary = ">=131.0.6765.0.0,<132"
easyocr = ">=1.7.0,<2"
openpyxl = ">=3.1.5,<4"
pandas = ">=2.2.3,<3"

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest tests/"

[feature.lint.dependencies]
ruff = "*"

[feature.lint.tasks]
lint = "ruff check --fix ."

[environments]
default = { features = ["test", "lint"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }
prod = { features = [], solve-group = "default" }

[target.osx-arm64.dependencies]
pyobjc-framework-cocoa = ">=10.3.1,<11"

[target.osx-arm64.pypi-dependencies]
pyobjc-framework-vision = ">=10.3.1, <11"

[target.osx-64.dependencies]
pyobjc-framework-cocoa = ">=10.3.1, <11"

[target.osx-64.pypi-dependencies]
pyobjc-framework-vision = ">=10.3.1, <11"
